/*
D&D 5e API

Testing CharacterDataApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_openapi_CharacterDataApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test CharacterDataApiService ApiAbilityScoresIndexGet", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var index string

        resp, httpRes, err := apiClient.CharacterDataApi.ApiAbilityScoresIndexGet(context.Background(), index).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test CharacterDataApiService ApiAlignmentsIndexGet", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var index string

        resp, httpRes, err := apiClient.CharacterDataApi.ApiAlignmentsIndexGet(context.Background(), index).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test CharacterDataApiService ApiBackgroundsIndexGet", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var index string

        resp, httpRes, err := apiClient.CharacterDataApi.ApiBackgroundsIndexGet(context.Background(), index).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test CharacterDataApiService ApiLanguagesIndexGet", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var index string

        resp, httpRes, err := apiClient.CharacterDataApi.ApiLanguagesIndexGet(context.Background(), index).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test CharacterDataApiService ApiProficienciesIndexGet", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var index string

        resp, httpRes, err := apiClient.CharacterDataApi.ApiProficienciesIndexGet(context.Background(), index).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test CharacterDataApiService ApiSkillsIndexGet", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var index string

        resp, httpRes, err := apiClient.CharacterDataApi.ApiSkillsIndexGet(context.Background(), index).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
