/*
D&D 5e API

Testing ClassResourceListsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_openapi_ClassResourceListsApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test ClassResourceListsApiService ApiClassesIndexFeaturesGet", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var index string

        resp, httpRes, err := apiClient.ClassResourceListsApi.ApiClassesIndexFeaturesGet(context.Background(), index).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test ClassResourceListsApiService ApiClassesIndexProficienciesGet", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var index string

        resp, httpRes, err := apiClient.ClassResourceListsApi.ApiClassesIndexProficienciesGet(context.Background(), index).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test ClassResourceListsApiService ApiClassesIndexSpellsGet", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var index string

        resp, httpRes, err := apiClient.ClassResourceListsApi.ApiClassesIndexSpellsGet(context.Background(), index).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test ClassResourceListsApiService ApiClassesIndexSubclassesGet", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var index string

        resp, httpRes, err := apiClient.ClassResourceListsApi.ApiClassesIndexSubclassesGet(context.Background(), index).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
