/*
D&D 5e API

Testing SubclassesApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_openapi_SubclassesApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test SubclassesApiService ApiSubclassesIndexFeaturesGet", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var index string

        resp, httpRes, err := apiClient.SubclassesApi.ApiSubclassesIndexFeaturesGet(context.Background(), index).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test SubclassesApiService ApiSubclassesIndexGet", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var index string

        resp, httpRes, err := apiClient.SubclassesApi.ApiSubclassesIndexGet(context.Background(), index).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test SubclassesApiService ApiSubclassesIndexLevelsGet", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var index string

        resp, httpRes, err := apiClient.SubclassesApi.ApiSubclassesIndexLevelsGet(context.Background(), index).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test SubclassesApiService ApiSubclassesIndexLevelsSubclassLevelFeaturesGet", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var index string
        var subclassLevel int32

        resp, httpRes, err := apiClient.SubclassesApi.ApiSubclassesIndexLevelsSubclassLevelFeaturesGet(context.Background(), index, subclassLevel).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test SubclassesApiService ApiSubclassesIndexLevelsSubclassLevelGet", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var index string
        var subclassLevel int32

        resp, httpRes, err := apiClient.SubclassesApi.ApiSubclassesIndexLevelsSubclassLevelGet(context.Background(), index, subclassLevel).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
